### ISSUE TITLE
Add asterism

### ISSUE THREAD

**Issue by jenstroeger** [CatharsisFonts/Cormorant#10]
It would be great to have an [Asterism](https://en.wikipedia.org/wiki/Asterism_(typography)) glyph as well, unicode U+2042.

**Comment by CatharsisFonts** [comment]
Done! I hope it looks right — I have no idea what it's supposed to look like. More or less aligned with the baseline, I assume?

**Comment by jenstroeger** [comment]
I would agree, but perhaps that shows once it's set on a page. Whenever [Typophile](http://typophile.com/) is being resuscitated then that would be an interesting topic. Thank you for adding it, curious to try it out!

**Comment by grzegorzrolek** [comment]
Hey Jens, try putting it on [TypeDrawers](http://typedrawers.com) in the meantime!
