### ISSUE TITLE
Difference between Cormorant and Cormorant Garamond?

### ISSUE THREAD

**Issue by orthoxerox** [CatharsisFonts/Cormorant#13]
Is the only difference between Cormorant and Cormorant Garamond that the latter has a tiny bit more condensed Cyrillic? I've installed both and printed out some specimens, and that's the only difference I've noticed.

**Comment by CatharsisFonts** [comment]
Hi Orthoxerox,

these are the differences between the Cormorant (top) and Cormorant Garamond (bottom). These propagate to related letters, of course. The main differences are larger apertures in /a and /e, and a more traditional shape for /g.

<img width="567" alt="screen shot 2016-04-24 at 11 47 50" src="https://cloud.githubusercontent.com/assets/13754106/14766631/67812430-0a12-11e6-87e0-407664d5985f.png">

Cheers, Christian

**Comment by orthoxerox** [comment]
Ah, thanks.
