### ISSUE TITLE
Consistency of font names

### ISSUE THREAD

**Issue by nclm** [CatharsisFonts/Cormorant#19]
The metadata names of the fonts aren’t set consistently. Some follows `Cormorant Style Weight`, some `CormorantStyle-Weight` (not taking italics into account). This is especially troublesome when it happens inside the same style, as with `CormorantUpright-Regular` vs `Cormorant Upright Bold`, or `Cormorant-Light` vs `Cormorant Bold`.

**Comment by CatharsisFonts** [comment]
That's very confusing. I'm not setting the metadata names myself; Glyphs is supposed to take care of that. I'm wondering whether the Bold weights are singled out because they're marked as the Bold of the Regular cuts? Does this problem only affect the Bold weights?

**Comment by CatharsisFonts** [comment]
There's a new release coming up soon. I wonder if this got fixed in the recent exports or if it's a deeper problem?

**Comment by CatharsisFonts** [comment]
Well, too late now. 😬
