### ISSUE TITLE
suggestion to add IPA characters

### ISSUE THREAD

**Issue by jandhau** [CatharsisFonts/Cormorant#20]
Hi Christian, 

Is there any way to add the phonetic characters of IPA?
Since they are mostly based on latin characters which are turned around or flipped etc., maybe it's not too hard to include them?  ʔǝŋɲɾʧɨɔɛʃʤɸɣβɡɑɐɒʙðɕʑɻɚ   I know every linguist would be eternally grateful :)

On the other hand, from your experience, what do you think would be the best fallback font for characters that aren't available in Cormorant?  Aside from IPA I'm also thinking about Greek (I saw the other threads), every once in a while it happens that a Greek word shows up in my text, and it'd be great to know which alternatives might be best to use so that it doesn't disturb the eye  (I tried with [standard] Garamond but it's a little too heavy for my taste). 

Other than that I can only say your font is the prettiest serif out there.  Thanks for such an awesome job!
Jan

**Comment by CatharsisFonts** [comment]
Hi jandhau,

IPA is _way_ larger than just the few symbols you mention, especially with all the combining marks... while I love IPA myself, I find it an utterly daunting task to implement it in a font. Maybe if Google or SIL or somebody paid me for it...?  ;o)

I have no experience with Greek fonts, I'm afraid. Maybe use a light Didone to at least get the contrast right?

Thanks for the kind words!  :)
