### ISSUE TITLE
A Text version?

### ISSUE THREAD

**Issue by be5invis** [CatharsisFonts/Cormorant#25]
Being less Display

**Comment by CatharsisFonts** [comment]
That's what EB Garamond is for!  😬 

But I'm not opposed to the idea, it's just not a priority at the moment.

**Comment by jenstroeger** [comment]
You mean [this EB Garamond](http://www.georgduffner.at/ebgaramond/)?

**Comment by CatharsisFonts** [comment]
For example, though I believe that website hasn't been updated for a while. If I'm not mistaken, this is the most alive branch of it at this moment:
https://github.com/octaviopardo/EBGaramond12
