### ISSUE TITLE
QA review for Google Fonts

### ISSUE THREAD

**Issue by m4rc1e** [CatharsisFonts/Cormorant#26]
Hey,

We can't release this onto Google Fonts, until some issues have been fixed:

## Multiple Master compatibility issues:
**Uprights:**
three.sups
![screen shot 2017-01-10 at 11 29 25](https://cloud.githubusercontent.com/assets/7525512/21804703/3d87fa94-d728-11e6-8d81-f73cc137f1fa.png)

For Qaing your fonts, you can use my [QA tool](https://github.com/m4rc1e/mf-glyphs-scripts).

## Other minor issues include:
Aacute.ss13.001 should be deleted

cc @davelab6

**Comment by CatharsisFonts** [comment]
Thanks! I've fixed the mismatch in the Uprights, new commit coming soon. Should I make a new release for this or just sneakily replace the files in the previous release...?  😬 

Does this review cover all fonts or only the Uprights?

**Comment by m4rc1e** [comment]
Increase by 0.001

**Comment by CatharsisFonts** [comment]
Well, I mapped the release number v3.3 to the Glyphs-internal version number 3.003, so to remain consistent I guess I should pick v3.4 next. Or I could call it v3.3.001 but raise the internal one to 3.004, but I don't feel too comfortable with that.

**Comment by m4rc1e** [comment]
3.004 then. There should only be 3 minor digits.

**Comment by moyogo** [comment]
Why not take the opportunity to make versions be the same: v3.301.

**Comment by CatharsisFonts** [comment]
That's not a bad idea. I just spent a lot of time exporting all of the fonts with 3.004 in the metadata, though. I suppose I should automate that someday.

Is it important?

**Comment by m4rc1e** [comment]
Apologies, @moyogo is correct. 

The current version is 3.300 so it should be 3.301

@moyogo thanks

**Comment by CatharsisFonts** [comment]
Alright, I changed the number to 3.301. Commit is up. Shall I release it, or is the QA not done yet?

**Comment by m4rc1e** [comment]
Thanks @CatharsisFonts, I'll have a look at it tomorrow.

Cheers!
