### ISSUE TITLE
no more pull requests please

### ISSUE THREAD

**Issue by m4rc1e** [CatharsisFonts/Cormorant#27]
Hey,

I should have the mastering finished off tomorrow. I'd appreciate it if you could hold off doing any more modifications. 

Since we're dealing with a shit tonne of ttfs, it make merge conflicts a huge possibility.

cc @davelab6

**Comment by davelab6** [comment]
@m4rc1e I suggest that moving into 2017 we aim to have you prep GF PRs based on github releases (in this case, from https://github.com/CatharsisFonts/Cormorant/releases) such that you don't get caught in the middle of a flurry of modifications; of course having you do a release-candidate check with the designer on their master branch can be helpful too, especially for less mature projects than this, but I think that could make sense here....

**Comment by m4rc1e** [comment]
Yeah we need a much better way of handling this.

I'll collect some thoughts in the coming weeks.

**Comment by CatharsisFonts** [comment]
Do you want me to issue a new release with the changes since QA, or are you sticking to the live version?
