### ISSUE TITLE
Large kerning in Cormorant Infant (Cyrillic)

### ISSUE THREAD

**Issue by fingli** [CatharsisFonts/Cormorant#31]
OS: Windows 10, x64
Software: MS Word 2016

I tried only Cormorant Infant as it's supports Bulgarian glifs. 
The issue: There is too much white space after certain capital letters when one use Cyrillic. Thhis makes the  letter appear like a standalone but not a part of the word itself. Namely the letters are: М, Р, Т and X in Cyrillic. This large kerning appears only in regular weight, in itallic, bold & bolditallic they are OK. 

Applying a screenshot from my Word. Underlining is mine in order to be easier to see, if one is not familiar with Cyrillic. 
![1a](https://cloud.githubusercontent.com/assets/420475/22611016/142b3e7a-ea71-11e6-81f2-c0241abc3321.png)

**Comment by CatharsisFonts** [comment]
ARGH! I guess this is still related to the Glyphs bug. I wonder how many more problems are hiding in those exports. I'll try to fix it as soon as possible.

**Comment by CatharsisFonts** [comment]
Should be fixed in the live commit. Can you confirm?

**Comment by fingli** [comment]
Perfect :sparkles:

![a1](https://cloud.githubusercontent.com/assets/420475/22618348/ad92c580-eae2-11e6-81c7-23110cb3c283.png)
