### ISSUE TITLE
Missing U+2043

### ISSUE THREAD

**Issue by jenstroeger** [CatharsisFonts/Cormorant#32]
I just noticed that the [HYPHEN BULLET](https://codepoints.net/U+2043) codepoint is missing from the font. Could that one be added?

**Comment by CatharsisFonts** [comment]
Sure. I'm not familiar with the character, though. Should it look identical to the hyphen? Should it be horizontal when the regular hyphen is tilted? Should the spacing be different?

**Comment by jenstroeger** [comment]
I saw it used to replace the bullet in a bullet list, and Word often replaces these bullets with actual hyphens. Alas, they’re not.

I’d probably go for a simple horizontal line without much spacing, assuming that the spacing is handled by the typesetting software when it sets the lists (and, thus, adds sufficient space).

**Comment by CatharsisFonts** [comment]
Included it in the most recent commit. Does that work for you?

**Comment by jenstroeger** [comment]
Yes, thank you, that’s great 👍
