### ISSUE TITLE
Cormorant ligatures

### ISSUE THREAD

**Issue by alnbyr** [CatharsisFonts/Cormorant#33]
Hello,
I'm using your fonts Cormorant. I'm working on Mac system, using Pages application. I am a basic user mac, not a specialist in software.
Cormorant standard ligatures are actives (fi, ff, fl, etc.) but I cannot use discretionary ligatures (st, rt, sp, etc.).

What can I do to use these discretionary ligatures? I downloaded the "Cormorant_Install" ZIP and I installed the TrueType font files (.ttf).
Did I do a mistake? Is there a special operation to do to update the fonts? 

Thanks by advance for your help.
Regards

**Comment by CatharsisFonts** [comment]
Sounds like a Pages problem rather than a font problem... have you tried the typography dialog (Cmd T)? By default, Standard Ligatures should be on and Discretionary Ligatures off. Can't check right now. Google might help. 

Cheers

**Comment by moyogo** [comment]
Format > Fonts > Show Fonts (Cmd+T)
then in the Font window:
⚙  >  Typography...
then in the Typography window:
Ligatures > Rare Ligatures

**Comment by alnbyr** [comment]
It was simple, but I did know this operation.
Now it’s perfect, your fonts are beautiful, refined, modern and make my documents so luxurious. 

Thanks you very much for your help, and thanks for this high-quality fonts.

**Comment by CatharsisFonts** [comment]
Thanks moyogo for the help, and thanks alnbyr for the kind words. 😬
