### ISSUE TITLE
Small Caps : fonts unavailable

### ISSUE THREAD

**Issue by omakuva** [CatharsisFonts/Cormorant#35]
Thanks for the awesome attainment.

Can't get past this issue, w/o and w/ Cormorant SC installed.

This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017) (preloaded format=xelatex) restricted \write18 enabled.
entering extended mode
LaTeX2e <2017-04-15>

LaTeX Font Warning: Font shape `TU/Cormorant(0)/m/sc' undefined
(Font)              using `TU/Cormorant(0)/m/n' instead on input line 177.

LaTeX Font Warning: Some font shapes were not available, defaults substituted.

**Comment by CatharsisFonts** [comment]
Can you narrow down the problem? I'm not familiar with using external fonts in LaTeX. Have you actually seen any glitches in the compiled document? Are you using the latest release of Cormorant?

**Comment by omakuva** [comment]
Solved ! With the line adjustments _in italics_ : 

\setromanfont[%Letters=SmallCaps,
_SmallCapsFont=Cormorant SC, SmallCapsFeatures={Letters=SmallCaps},_
Mapping=tex-text, Numbers=OldStyle]{Cormorant}

Cf. https://tex.stackexchange.com/questions/135641/problem-with-small-caps-in-xelatex -- for a similar issue with Charis SIL font.

Yet : the alternative solution mentioned thereof _SmallCapsFeatures={Letters=SmallCaps}_ does not work.

Aa to your questions : no glitches ; the font-release adopted were those found yesterday at https://fonts.google.com/ -- 


Looking forward to further development on the EauDeGaramond side.

Best wishes.
