### ISSUE TITLE
repo filesize is huge

### ISSUE THREAD

**Issue by afincato** [CatharsisFonts/Cormorant#42]
why not splitting it into submodules if you want to store everything on github?

i honestly just wanted the webfont without going over to google fonts, but here i am waiting 10 mins in order to `git clone` a repo amounting to more than 1 GB.

thanks for the work,
af

**Comment by RGB-es** [comment]
On the main repo page, Clone or download button → Download zip. You'll get the latest version of all fonts and the file is just 54 MiB.

**Comment by afincato** [comment]
yep thank you.

**Comment by CatharsisFonts** [comment]
Also, the releases offer a dedicated webfont download.
