### ISSUE TITLE
Glyph names

### ISSUE THREAD

**Issue by cmahte** [CatharsisFonts/Cormorant#47]
Starting from Cormorant regular, 

FontForge complains about glyph names when I build .otf fonts:
![screen shot 2018-11-02 at 6 41 31 am](https://user-images.githubusercontent.com/11809394/47913778-4c6ed900-de6b-11e8-9970-31affc9f6f5d.png)

But I don't see a ss13 to verify against. I suspect these are now in a character variant, but where? Font forge is pretty good about renaming glyphs, but these are invalid, so I want to check they did rename everywhere, because font forge doesn't deal well with names in feature tables that don't have glyphs. 

If the unlikely "actually not in a table" are true.. is this development, or dinosaur?

**Comment by CatharsisFonts** [comment]
Thanks for pointing that out. Some of the OpenType features were missing from the Cormorant glyphs files. I believe that happened a while ago with a Glyphs version that ate features. Looks like I hadn't recovered all of them. 

New commit coming up, I hope that will fix the problem.

Out of interest, what are you doing with FontForge...?

Cheers, Christian

**Comment by cmahte** [comment]
1. I'm working on the jalt table I mentioned in an earlier issue to put alternate "optical" or "hanging" justification into opentype feature jalt. This means initially alternate glyphs for punctuation with the sides adjusted and a kerning table to make them 'normal' in the middle of text, but 'hang' when they land on an edge. 

Cormorant is already huge, but properly implemented this also means alternates for angled capitals (W A V Y 7) and horizontally flat capitals (T L J) that do similar but more subtle shifts. If this jalt thing works, I'm investing in learning scripting to automagicate it, but as of now I'm keying it all by hand. Once I go to scripting I can deal with 100 flavors of A. For development,  proving the punctuation hangs is good enough. 

2. Since I'm opening the font up, I've also messed with all space widths a bit (related to justification, I'm setting them closer to mathematic proportions.) I don't like what I've done so far, so I'll probably put it all back. 

3. And on the subject of spaces I'm pushing the addition of backspace Ux0008 a bit further.  Ux0008 doesn't work in LibreOffice as it is (LibreOffice ignores it), so I'm including it in the jalt table to a non-control glyph (EBAC). That is Libreoffice presents a blank glyph. I can move the cursor over it and there's a position for it, but kerning or tracking that glyph has no effect. by alternating it for a 'private use' glyph, early testing suggests I can have the font have a huge negative kern value to actually space backward. This is still untested as a value inside the font.  My use for Ux0008 backspace is related to optical vs. strict margins. When a biblical verse number occurs at the start of a line of poetry, it hangs outside the start of the row of poetry. So, It's technically correct that it only works when I'm in optical margin mode, not strict margin mode.

4. I haven't got to this yet, but superscripts need digits, lowercase letters parens and dashes.  I noticed a hole or two in the superscripts unicode locations when working on spaces. I'll suggest a complete list when I get there. 
____
0. Import fixes. Opening the font up in Font Forge causes issues. I suppose its rounding errors between the programs, but I get a lot of 'non-integral points' and 'point not at extrema' errors that have to be re-integered and re-extremed. (I started with Cormorant Garamond, which had about 1500 errors in the regular face. I switched to Cormorant, and it only had about 120 errors in the regular face.) Going through these, the fix looks exactly like the problem, so I'm guessing its a 1 <>.99999 kind of error. However, fixing these issues breaks truetype hinting as soon as I start (Fontforge didn't warn me at first it deletes them when I change the glyph, but now it does.) So I'm autohinting/autoinstructing the font. In redoing the hinting and instructing, I have no idea what it means, so I've probably wiped out a tiny bit of the 'pretty', but I don't have the glyphs program, and I'm developing on linux for linux, so the truetype stuff is really thrown out anyway. (my primary output is postscript OTF.)

**Comment by cmahte** [comment]
The developer on Google play is listed as VSIONTEQ.  They aren't related to
the church. They have only a few items on the play store, so this is either
an obfuscation layer of a larger outfit or a small org.  But.. they are
likely the ones who can fix the contact inside the android app.

http://vsionteq.com/support.php
I googled this, but the address listed at the bottom of this page here is
the same that appears on the play store listing.

They are using the sword repo, and giving credit in the app. I don't
recognize the app itself, which is only saying it's not obviously based on
AndBible.  I haven't played with anything but AndBible or Bishop in
forever. if someone has a suggestion what it might be I can compare.

The app doesn't appear to have any 'contact crosswire for support' link...
but it does have a confusing pointer to a non-existent support link
followed immediately by a credit line to crosswire....

The credit line to Crosswire appears below a confusing statement how to
contact support, however, theres no 'support' link on the webpage that
links, so reading the line again, the next place to click is on the
crosswire acknowledgement below that. (link for the word support goes to
the TLD http://www.omegabible.com ) For non-english speakers, it's not
clear what that line about emailing support says, and it could be read to
contact crosswire for limited English speakers.

The facebook link above the support link goes here: (
https://www.facebook.com/OmegaDigiBible/ )

Related images:

[image: Screen Shot 2018-11-02 at 10.25.05 AM.png]
[image: Screen Shot 2018-11-02 at 10.25.59 AM.png]

[image: Screenshot_20181102-103852.png]

**Comment by cmahte** [comment]
I apologize.. google insisted I wanted to send to you, even though I
stopped and restarted this email 2x.

**Comment by ArchangeGabriel** [comment]
@cmahte You can delete both comments on GitHub web interface. ;)

**Comment by cmahte** [comment]
Thanks.
