### ISSUE TITLE
Weight Axis variable font

### ISSUE THREAD

**Issue by pichotta** [CatharsisFonts/Cormorant#49]
@CatharsisFonts 

Hello Christian,

The Google fonts team would love to see a variable fonts version of ‘Cormorant'. They have commissioned us @TypeNetwork to work on upgrading a number of font projects to be variable fonts with a single weight axis.

In order to achieve the highest quality and most efficient long term results we will be converting the source data from Glyphs to UFO. The new source data will be generated in the RoboFont environment using fontmake and ttfautohint. There has been progress on tools to make an easy path to move between the Glyphs and Robofont environment.

During the process we will be looking to improve any errors while preserving how the font appears and renders on different platforms.

We have started by making a fork off of this git repository. The upgrade will be completed for you in the near future. When the proposed final font is approved by Google will you accept a pull request?

To confirm, are the **.glyphs source files** on this git repository the most current data?
CormorantRoman.glyphs
CormorantItalic.glyphs
CormorantUpright.glyphs

We hope this answers some of your questions about the process. Please let us know if you have any additional comments.

Best Regards,

Jill Pichotta
Vice President
Type Network
pichotta@typenetwork.com

**Comment by CatharsisFonts** [comment]
Dear Jill,

in principle, I am happy to help you turn Cormorant into a
variable font typeface.  Are you proposing that the Cormorant
source files be permanently ported to UFO, though?  I'm not
too happy about that prospect...  if the conversion between
UFO and Glyphs is lossless, can't we keep Glyphs as the master
format?

Cheers, Christian

**Comment by pichotta** [comment]
The variable weight axes project does involve porting the data to UFOs. There is a mechanism to port it back to Glyphs using 'ufo2glyphs'.

The Cormorant family was taken off our project list.
