### ISSUE TITLE
c_t missing unicode reference google fonts Cormorant Garamond

### ISSUE THREAD

**Issue by gessel** [CatharsisFonts/Cormorant#54]
I was trying to get c_t (0x100ee) to substitute for "et" as a ligature and have thus far been stymied.
I see it is the first entry in the "dlig" table, but I can't get it or any other discretionary ligatures to render in either Chrome nor FF, Win nor Ubuntu testing as:

https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Fundamentals
HTML Input:
```
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,500;1,500&display=swap" rel="stylesheet">
<p class="ligs">dlig: ct ffu fu Qy liga: fb ff ffb</p>
```  
CSS Input
```
.ligs {
 font-size: 50px;
font-family: 'Cormorant Garamond', serif;
  font-variant-ligatures: discretionary-ligatures;
}
```
output:
![image](https://user-images.githubusercontent.com/3670635/91064807-6da04b00-e638-11ea-978e-70a09026bf8a.png)

I'd expect:
![image](https://user-images.githubusercontent.com/3670635/91065077-bbb54e80-e638-11ea-82bd-b88f3bf042b8.png)

I had thought to simply call it by HTML or Unicode, but the standard values cited U+1F670/&#x1F670; aren't assigned in the font file.

Any hints?
Thanks!

**Comment by thlinard** [comment]
https://github.com/google/fonts/issues/1582

**Comment by CatharsisFonts** [comment]
Thanks Thomas, didn't know about that!

BTW, is there historic precedent for using c_t for &...?

**Comment by thlinard** [comment]
> BTW, is there historic precedent for using c_t for &...?

No, the two ligatures are unrelated. & (U+0026 AMPERSAND) is for "e+t". Very common ligature in 17th century English and French books. For example, on the cover of this 1607 book, there are two & (and a c+t ligature):
https://fr.wikisource.org/wiki/Livre:Antoine_Loysel,_Institutes_coustumieres,_1607.djvu

Or this 1763 book (&c. = etc.):
https://en.wikisource.org/wiki/Page:Ruffhead_-_The_Statutes_at_Large_-_vol_4.djvu/287

**Comment by CatharsisFonts** [comment]
Maybe the Cormorant Italic ampersand might be a better choice then, since it mirrors that form.

**Comment by gessel** [comment]
Thanks - this is, indeed what I need.  Also, thanks for the detail on not getting dlig tables from googlefonts. 
![image](https://user-images.githubusercontent.com/3670635/91435922-d1f91f80-e86f-11ea-8b33-36160ecc7e70.png)

The ligature from Adobe Garamond Pro that sent me off on the tangent is:

![image](https://user-images.githubusercontent.com/3670635/91436206-5186ee80-e870-11ea-9821-a29f65a2ec49.png)
