### ISSUE TITLE
U+220F N-ARY PRODUCT and U+2211 N-ARY SUMMATION are too short

### ISSUE THREAD

**Issue by dscorbett** [CatharsisFonts/Cormorant#56]
U+220F N-ARY PRODUCT and U+2211 N-ARY SUMMATION should descend below the baseline, which is the convention for <var>n</var>-ary operators. The current glyphs would be appropriate for U+03A0 GREEK CAPITAL LETTER PI and U+03A3 GREEK CAPITAL LETTER SIGMA instead. Here they are, with ⟨R⟩ for comparison:
![R∏∑](https://user-images.githubusercontent.com/1124347/94874129-2cf9d580-041f-11eb-904e-8711adac529c.png)

**Comment by CatharsisFonts** [comment]
Good points; I'll put that on my to-do list!

**Comment by CatharsisFonts** [comment]
How about this, then? New commit coming soon.
<img width="697" alt="Screenshot 2020-10-06 at 00 05 00" src="https://user-images.githubusercontent.com/13754106/95139696-60b16400-076d-11eb-9c81-8894307537d2.png">
