### ISSUE TITLE
Problems with latest build

### ISSUE THREAD

**Issue by RGB-es** [CatharsisFonts/Cormorant#57]
As you can see from the screen-shot, the latest build have some over abundance of diacritics ;) (tested with OpenType variant). The build from September 10 had no problems.
 
![image](https://user-images.githubusercontent.com/7756783/95387229-b4988600-08f0-11eb-9356-bb020b9873ae.png)

**Comment by CatharsisFonts** [comment]
ARGH! That's gotta be a problem of the batch export script. I had to update it to work with the Glyphs 3 beta. I'll try to undo the damage as soon as possible.

**Comment by CatharsisFonts** [comment]
Better now?

**Comment by RGB-es** [comment]
> Better now?

Perfect!! (I don't know how to close an issue, sorry)
