### ISSUE TITLE
Spacing of letters with diacritics in webfont files

### ISSUE THREAD

**Issue by f-parmentier** [CatharsisFonts/Cormorant#59]
Hi, I found out that there is an issue of spacing with letters including diacritics on webfont files for CormorantGaramond (.woff and .woff2, I didn't check the .eot). As you can see on the images below, the right side bearing of the letter é is too wide in Regular, Italic, Medium, Medium italic, SemiBold and SemiBold italic (not Thin nor Bold nor their italics).

![cormorant](https://user-images.githubusercontent.com/70858321/100556051-b0a93480-329f-11eb-87fe-fed172389942.jpg) Thin
![cormorant2](https://user-images.githubusercontent.com/70858321/100556052-b141cb00-329f-11eb-93f5-eb8cf220c5b9.jpg) Thin italic
![cormorant3](https://user-images.githubusercontent.com/70858321/100556053-b1da6180-329f-11eb-87c9-185c727a13bd.jpg) Regular
![cormorant4](https://user-images.githubusercontent.com/70858321/100556054-b1da6180-329f-11eb-9e25-9a547e4c4dbf.jpg) Italic
![cormorant5](https://user-images.githubusercontent.com/70858321/100556055-b272f800-329f-11eb-9585-cf075ed6fc9d.jpg) Medium
![cormorant6](https://user-images.githubusercontent.com/70858321/100556012-85264a00-329f-11eb-8ab0-2d257bdb1ec8.jpg) Medium italic
![cormorant7](https://user-images.githubusercontent.com/70858321/100556011-85264a00-329f-11eb-940f-d7093c8f97d0.jpg) SemiBold
![cormorant8](https://user-images.githubusercontent.com/70858321/100556010-848db380-329f-11eb-925a-6f0439afb0d1.jpg) SemiBold italic
![cormorant9](https://user-images.githubusercontent.com/70858321/100556008-83f51d00-329f-11eb-9fc3-b686fdbd2bf4.jpg) Bold
![cormorant10](https://user-images.githubusercontent.com/70858321/100556009-848db380-329f-11eb-96ea-4e815a368a6a.jpg) Bold italic

The issue concerns every lowercase with diacritic(s), I hope it's not too much of an update…

Thank you in advance!

Florian

**Comment by CatharsisFonts** [comment]
Is this a recent development? It certainly doesn't show up on Google Fonts... I wonder whether it's simply an exporting issue. I'll look into it.

**Comment by CatharsisFonts** [comment]
Apparently, I hadn't exported the webfonts in years... can you try with the new commit?

**Comment by f-parmentier** [comment]
Yes, problem solved! 
Thank you so much for your prompt reply, my website is going to look much more better now 💯

**Comment by CatharsisFonts** [comment]
Glad I could help! :)
