### ISSUE TITLE
Spacing between Q and certain numbers (Garamond Italic)

### ISSUE THREAD

**Issue by JesusMcCloud** [CatharsisFonts/Cormorant#60]
Just noticed that the combination of uppercase Q and some numbers does nor work well (see below)
Q3 and Q5, for example, result in very close strokes, which requires huge font sizes to even be clearly recognizable as not a ligature. Otherwise, Cormorant is not only the most aesthetically pleasing font family I have ever come across; it also covers a ridiculously extensive character and feature set!

![image](https://user-images.githubusercontent.com/5648377/106878226-fdfbb500-66d9-11eb-8b3c-dc0d49e7f9e2.png) ![image](https://user-images.githubusercontent.com/5648377/106878243-0227d280-66da-11eb-9842-ac418e85eaff.png) ![image](https://user-images.githubusercontent.com/5648377/106878257-05bb5980-66da-11eb-9c0e-e3c168c97ed5.png) ![image](https://user-images.githubusercontent.com/5648377/106878270-094ee080-66da-11eb-94a4-69ba2f3413db.png) ![image](https://user-images.githubusercontent.com/5648377/106878286-0d7afe00-66da-11eb-82c8-8d2bc35e05de.png)

**Comment by CatharsisFonts** [comment]
Hi Bernd, 

glad you like Cormorant! I added some positive kerning to Q3, Q5, Q7, and Q9. Better now?
<img width="807" alt="Screenshot 2021-02-04 at 11 51 40" src="https://user-images.githubusercontent.com/13754106/106884983-4c14b680-66e2-11eb-84d1-bf015ff2ab56.png">


Cheers, Christian

**Comment by JesusMcCloud** [comment]
Small things do make a big difference–even at text sizes!
Thank you very much, I never expected this to be fixed so fast (and in such a settle manner), awesome!
Is there any reason not to use the builds from the master branch in production?

**Comment by CatharsisFonts** [comment]
I think the current master build should be production-ready. Do tell me if you find any regressions.
