### ISSUE TITLE
No Serbian glyphs in italic style

### ISSUE THREAD

**Issue by VeskoRadic** [CatharsisFonts/Cormorant#62]
Hi.
I think that locl feature missing Serbian language in all italic variants.
The Serbian variant of glyphs exists in the lookup table, but the Macedonian language was probably set by mistake.

![image](https://user-images.githubusercontent.com/63882439/113489337-f1ba8b00-94c3-11eb-978d-0a61eeb772ba.png)

I noticed this when I tried to use a font in HTML. I had to set the language to Macedonian or activate stylistic set ss09 in order for the letters to be displayed correctly.

Sorry for bad English :(.

Vesko

**Comment by CatharsisFonts** [comment]
Thanks for pointing this out. The automatic generation of the LOCL feature was disabled in the Italic for some reason. I'll upload a corrected version as soon as the export is finished.

**Comment by VeskoRadic** [comment]
No problem.
As far as I'm concerned, we can close this.
Anyway, I have to say this is one of the most beautiful fonts I've seen recently. Great job.
