### ISSUE TITLE
Italic Kerning between Capital 'A' and Some Numbers

### ISSUE THREAD

**Issue by JesusMcCloud** [CatharsisFonts/Cormorant#63]
Hi! Sorry to bother with kerning again; I'm not even sure if this is a real issue, whether it it makes sense to 'fix' it or if it's just in my mind, but italic combinations like _A1_, _A2_,  _A3_,  _A4_,  _A5_ seem inconsistently kerned when using oldstyle numerals:

![image](https://user-images.githubusercontent.com/5648377/116698394-9c8b6f80-a9c4-11eb-81f5-410970f7c989.png)

Regular (Non-Italic) cuts present a more consistent look, but I'm pretty sure its all a psychological thing in the first place and the distances between letters and numbers are consistent (although I have not checked)
![image](https://user-images.githubusercontent.com/5648377/116698583-d52b4900-a9c4-11eb-9b33-5dc100c01d02.png)

**Comment by CatharsisFonts** [comment]
> but I'm pretty sure its all a psychological thing in the first place and the distances between letters and numbers are consistent (although I have not checked)

The distances are entirely irrelevant — what matters is what they look like, which is very much a «psychological thing»!

Does this work for you? I added some positive kerning between A and 4 and some negative between A and {3, 5, 7}.
<img width="722" alt="Screenshot 2021-04-30 at 15 12 44" src="https://user-images.githubusercontent.com/13754106/116700397-06a51400-a9c7-11eb-9c98-96465956bee5.png">
<img width="552" alt="Screenshot 2021-04-30 at 15 14 45" src="https://user-images.githubusercontent.com/13754106/116700411-09076e00-a9c7-11eb-840e-b63513e0c63c.png">

**Comment by JesusMcCloud** [comment]
That looks really great, thanks!

**Comment by CatharsisFonts** [comment]
OK, I'll export and commit.
