### ISSUE TITLE
Missing Pāli character

### ISSUE THREAD

**Issue by jenstroeger** [CatharsisFonts/Cormorant#7]
It seems as if two Pāli characters are missing: U+1E40 (Ṁ) and U+1E41 (ṁ). Would be great if they were added!

**Comment by CatharsisFonts** [comment]
I do have them in my source files. Do they not export?

**Comment by jenstroeger** [comment]
Not in the .zip file I downloaded a few days ago, but I didn't build the fonts from source.

**Comment by CatharsisFonts** [comment]
It's been part of the typefaces for months. I can certainly see it in the OTFs.

**Comment by jenstroeger** [comment]
That is odd. Here's the OTF I've installed last night: Version 1.000;PS 000.005;hotconv 1.0.70;makeotf.lib2.5.58329

And here's a screen shot using it in Font Book on my Mac.
![comorant](https://cloud.githubusercontent.com/assets/12053937/10118086/9153624a-6423-11e5-9b31-9c06da0bc8d1.jpg)

**Comment by CatharsisFonts** [comment]
ARGH!  Sorry Jens, I've been looking at M/m with dot *below* rather than above all this time. I've added the characters you requested now, they're in the TTF version of the live instance and will be part of the next release. Sorry for the brain fail.
