### ISSUE TITLE
Missing upright build on latest master  (January 6, 2023) 

### ISSUE THREAD

**Issue by RGB-es** [CatharsisFonts/Cormorant#70]
Downloading the latest builds from mater I noticed that the upright version is missing.

**Comment by CatharsisFonts** [comment]
OMG, you're right! I hadn't noticed... I think it dropped under the carpet when we switched to the Google Fonts directory structure.

I added it back in from a backup. Thanks for noticing!

**Comment by RGB-es** [comment]
Thanks to you, for all your gorgeous fonts!
