### ISSUE TITLE
Interpolation problems in `Cormorant[wght].ttf`

### ISSUE THREAD

**Issue by behdad** [CatharsisFonts/Cormorant#72]
Hello!

This is an automatically-generated report about possible interpolation problems in `Cormorant[wght].ttf`, as found in the Google Fonts catalog.

The particular version of the font that was tested was [archive:](archive:).

To download a PDF version of this report with helpful visuals of the problems, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/raw/8ce3e0535f17cd069e91df45e252462bf74a2cc4/reports/Cormorant%5Bwght%5D.ttf.pdf); Or to view it on the GitHub website, click [here](https://github.com/behdad/google-fonts-ofl-interpolatable-results/blob/8ce3e0535f17cd069e91df45e252462bf74a2cc4/reports/Cormorant%5Bwght%5D.ttf.pdf).

The report follows:
```
Glyph colonmonetary was not compatible:
  Masters: '', 'wght=700.0':
    Contour order differs: [0, 1, 2, 3, 4] in '', [3, 1, 2, 0, 4] in 'wght=700.0'
```

This report was generated using the `fonttools varLib.interpolatable` tool.  We understand that sometimes the tool generates false-positives.  Particularly for more complicated font designs.  If you did not find this report useful, please apologize and ignore & close it.

To give feedback about this report, please file an issue or open a discussion at [fonttools](https://github.com/fonttools/fonttools).

**Comment by CatharsisFonts** [comment]
Should be fixed now.

**Comment by behdad** [comment]
Thanks.
