### ISSUE TITLE
Problem with weight axis in variable font

### ISSUE THREAD

**Issue by drs-p** [CatharsisFonts/Cormorant#73]
Hi,

I noticed an issue with the weight axis in the variable font (v4.001, both Roman and Italic). The font claims that the wght axis runs from 40 to 80. This is in itself unusual; the "usual" values are 300 for Light, 400 for Regular, 500 for Medium, 600 for Semibold and 700 for Bold. But the real problem is that wght=48 already corresponds to the Bold master; higher values don't give a bolder font. So the full range of weights is contained in the (tiny) interval from 40-48.

**Comment by kenmcd** [comment]
The v4.001 from here in the repo has some issues.
Among other things, the issue appears to be the instances are duplicated three times in the `fvar` table - which is probably causing the `40-48` issue in your application (even the odd axis settings should have worked without the duplicates).
And it appears there is some duplicate entries in the STAT table also.
These fonts are just not going to work.

Try the version from Google Fonts (v4.000).
https://fonts.google.com/specimen/Cormorant/
It looks like it has been fixed.

**Comment by CatharsisFonts** [comment]
I believe those are the variable fonts I generated with Glyphs. I don't know anything about variable fonts, so I'm not surprised if they don't come out well. The variable fonts on Google Fonts are generated by @yanone with the Google tools (I'm not sure why they're not in this repo as well?).
In any case, I should probably delete my own variable fonts so people don't try to use them?

**Comment by yanone** [comment]
No, I actually only worked on Ysabeau, not Cormorant.

It appears is though @m4rc1e had last generated the Google Fonts fonts on May 6th 2022, and you deleted them and replaced them with your own versions on January 6th 2023: https://github.com/CatharsisFonts/Cormorant/commits/master/fonts/variable

For Ysabeau I had made a separate /googlefonts folder in the repository to differentiate between the fonts you generate yourself and the GF versions, which I think makes sense this way in your case.
