### ISSUE TITLE
Monospace pairing

### ISSUE THREAD

**Issue by crepererum** [CatharsisFonts/Cormorant#9]
The font(s) and the different styles are great, but sometimes a monospace font is required. It might be a little bit too much to ask for a monospace style, but can you recommend a (SIL licensed) monospace font which goes well together with Cormorant? I'm asking because your knowledge as a font designer might be better than just guessing around.

**Comment by CatharsisFonts** [comment]
Dear Marco, 
I have no experience with monospaced fonts outside of programming; you're probably better qualified to find one that fits. I certainly don't have any plans to make a monospaced version of Cormorant.
Cheers, Christian

**Comment by crepererum** [comment]
OK, thank you anyway. I'll try and report back.
